---
name: Linter

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  linter:
    uses: raven-actions/.workflows/.github/workflows/__linter.yml@main
    secrets: inherit
