---
name: Publish Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name that the major tag will point to
        required: true
      debug:
        type: boolean
        description: Debug mode
        required: false
        default: false

permissions: {}

env:
  DEBUG: ${{ inputs.debug || secrets.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_RUNNER_DEBUG || secrets.ACTIONS_STEP_DEBUG || vars.ACTIONS_STEP_DEBUG || false }}
  TAG_NAME: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

jobs:
  build-publish-tag:
    name: Build, Publish and Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🩺 Debug
        if: ${{ env.DEBUG == 'true' }}
        uses: raven-actions/debug@9dbdeb7eea607a7d73411895c65987e71d59a466 # v1.2.0
        with:
          vars-context: ${{ toJson(vars) }}
          needs-context: ${{ toJson(needs) }}
          inputs-context: ${{ toJson(inputs) }}

      - name: 🔑 Get Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: get-token
        with:
          app-id: ${{ secrets.ORG_BOT_APP_ID }}
          private-key: ${{ secrets.ORG_BOT_PRIVATE_KEY }}

      - name: ⤵️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: 🚧 Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: 10

      - name: 🚧 Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: 🔀 Install dependencies
        run: pnpm deps:ci

      - name: 🏗️ Build
        run: pnpm build:ci

      - name: 🤖 Get bot details
        id: bot-details
        uses: raven-actions/bot-details@ee8966a9ff6e7e42cbfc4a56b4ddb60a9d1b40a6 # v1.2.0
        with:
          bot-slug-name: ${{ steps.get-token.outputs.app-slug }}
          set-env: false

      - name: 🚀 Publish and Tag Action
        uses: ./
        with:
          github_token: ${{ steps.get-token.outputs.token }}
          tag_name: ${{ env.TAG_NAME }}
          latest: true
          git_commit_message: ${{ format('🚀 {0} release', env.TAG_NAME) }}
          git_author_name: ${{ steps.bot-details.outputs.name }}
          git_author_email: ${{ steps.bot-details.outputs.email }}
          git_committer_name: ${{ steps.bot-details.outputs.name }}
          git_committer_email: ${{ steps.bot-details.outputs.email }}
