---
name: Stale

on:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: raven-actions/.workflows/.github/workflows/__stale.yml@main
    secrets: inherit
